FROM python:3.13.3-slim-bookworm

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

RUN addgroup --system app && adduser --system --group app

ENV HOME=/home/app
ENV APP_HOME=/home/app/web
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV ENVIRONMENT=prod
ENV TESTING=0

COPY pyproject.toml uv.lock ./
RUN uv pip install --no-cache --system . && \
    uv pip install --no-cache --system gunicorn==23.0.0

COPY . .

RUN chown -R app:app $APP_HOME

USER app

CMD ["sh", "-c", "exec gunicorn --bind 0.0.0.0:$PORT app.main:app -k uvicorn.workers.UvicornWorker"]
